GitHub → backend/server.py → ✏️ Edit → bütün məzmunu sil → bu kodu yapışdır → Commit directly to main
from fastapi import FastAPI, APIRouter, HTTPException, Query, Depends, Request, Header
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorClient
from pydantic import BaseModel, EmailStr
from typing import Optional, List
from datetime import datetime, timezone, timedelta
from pathlib import Path
import os
import time
import logging
import asyncio
import base64
import uuid
import bcrypt
import jwt
import yt_dlp
import httpx

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / ".env")

mongo_url = os.environ["MONGO_URL"]
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ["DB_NAME"]]

JWT_SECRET = os.environ.get("JWT_SECRET", "ryhavean-youtube-secret-change-me")
JWT_ALGO = "HS256"
JWT_EXPIRE_DAYS = 30

ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", "ravenhadjiyevh@gmail.com")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "ItWS*]iD)%$mSGa!")

app = FastAPI(title="Ryhavean YouTube")
api = APIRouter(prefix="/api")
bearer = HTTPBearer(auto_error=False)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("ryhavean-yt")

# ==================== YouTube cookies (auto-converter) ====================
YT_COOKIES_PATH = "/tmp/yt_cookies.txt"
YT_COOKIES_FILE: Optional[str] = None

def _normalize_cookies(raw: bytes) -> Optional[bytes]:
    try:
        text = raw.decode("utf-8", errors="ignore").strip()
    except Exception:
        return None
    if not text:
        return None

    first_lines = "\n".join(text.splitlines()[:5])
    if first_lines.startswith("# Netscape") or "# HTTP Cookie File" in first_lines:
        return raw
    sample_line = next((ln for ln in text.splitlines() if ln and not ln.startswith("#")), "")
    if sample_line.count("\t") >= 6:
        return raw

    expiry = int(time.time() + 86400 * 365)
    out_lines = ["# Netscape HTTP Cookie File", "# generated by ryoutube auto-converter"]

    if text.startswith("[") or text.startswith("{"):
        try:
            import json as _json
            data = _json.loads(text)
            if isinstance(data, dict):
                data = [data]
            for c in data:
                domain = c.get("domain") or ".youtube.com"
                if not domain.startswith("."):
                    domain = "." + domain.lstrip(".")
                path = c.get("path", "/")
                exp = int(c.get("expirationDate") or expiry)
                name = c.get("name", "")
                value = c.get("value", "")
                if not name:
                    continue
                out_lines.append(f"{domain}\tTRUE\t{path}\tFALSE\t{exp}\t{name}\t{value}")
            if len(out_lines) > 2:
                return ("\n".join(out_lines) + "\n").encode("utf-8")
        except Exception:
            pass

    if ";" in text and "=" in text:
        if text.lower().startswith("cookie:"):
            text = text.split(":", 1)[1].strip()
        for pair in text.replace("\n", ";").split(";"):
            pair = pair.strip()
            if not pair or "=" not in pair:
                continue
            name, _, value = pair.partition("=")
            name, value = name.strip(), value.strip()
            if not name:
                continue
            out_lines.append(f".youtube.com\tTRUE\t/\tFALSE\t{expiry}\t{name}\t{value}")
        if len(out_lines) > 2:
            return ("\n".join(out_lines) + "\n").encode("utf-8")

    return None

_b64 = os.environ.get("YT_COOKIES_B64", "").strip()
if _b64:
    try:
        decoded = base64.b64decode(_b64)
        normalized = _normalize_cookies(decoded)
        if normalized is None:
            logger.warning("[cookies] YT_COOKIES_B64 format not recognized")
        else:
            with open(YT_COOKIES_PATH, "wb") as _f:
                _f.write(normalized)
            YT_COOKIES_FILE = YT_COOKIES_PATH
            logger.info("[cookies] Loaded YouTube cookies (normalized to Netscape)")
    except Exception as e:
        logger.warning(f"[cookies] Failed to decode YT_COOKIES_B64: {e}")

# Locked desktop UA when cookies are loaded (cookie+UA fingerprint stable)
LOCKED_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/131.0.0.0 Safari/537.36"
)
FALLBACK_UA = (
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1"
)

_CLIENTS_WITH_COOKIES = ["web"]
_CLIENTS_NO_COOKIES = ["ios", "android", "web_safari", "web"]

def _yt_opts(extra: dict) -> dict:
    base = {
        "quiet": True, "no_warnings": True, "skip_download": True,
        "noplaylist": True, "socket_timeout": 20,
        "retries": 1, "fragment_retries": 1,
        "user_agent": LOCKED_UA if YT_COOKIES_FILE else FALLBACK_UA,
        "extractor_args": {
            "youtube": {
                "player_client": _CLIENTS_WITH_COOKIES if YT_COOKIES_FILE else _CLIENTS_NO_COOKIES,
            }
        },
    }
    if YT_COOKIES_FILE:
        base["cookiefile"] = YT_COOKIES_FILE
    base.update(extra)
    return base

def _make_search_opts():
    return _yt_opts({"extract_flat": True, "default_search": "ytsearch", "socket_timeout": 15})

def _make_stream_opts():
    return _yt_opts({
        "format": "best[ext=mp4][acodec!=none][vcodec!=none]/best[acodec!=none][vcodec!=none]/best",
    })

# ==================== Two-tier cache ====================
_MEM_CACHE: dict = {}
TTL_FEATURED = 60 * 60 * 6
TTL_SEARCH = 60 * 30
TTL_STREAM = 60 * 60 * 4
TTL_INFO = 60 * 60 * 24

def _mem_get(key):
    v = _MEM_CACHE.get(key)
    if not v: return None
    exp, data = v
    if time.time() > exp:
        _MEM_CACHE.pop(key, None); return None
    return data

def _mem_set(key, data, ttl):
    _MEM_CACHE[key] = (time.time() + ttl, data)

async def _db_cache_get(key):
    doc = await db.yt_cache.find_one({"_id": key})
    if not doc or doc.get("expires_at", 0) < time.time(): return None
    return doc.get("data")

async def _db_cache_set(key, data, ttl):
    await db.yt_cache.update_one({"_id": key},
        {"$set": {"data": data, "expires_at": time.time() + ttl,
                  "updated_at": datetime.now(timezone.utc).isoformat()}}, upsert=True)

async def cache_get(key):
    hit = _mem_get(key)
    if hit is not None: return hit
    hit = await _db_cache_get(key)
    if hit is not None:
        _mem_set(key, hit, 60 * 5)
        return hit
    return None

async def cache_set(key, data, ttl):
    _mem_set(key, data, min(ttl, 60 * 30))
    await _db_cache_set(key, data, ttl)

# ==================== Rate-limited yt-dlp gateway ====================
_YT_SEMAPHORE = asyncio.Semaphore(2)
_LAST_CALL_TS = 0.0
_MIN_GAP = 1.0

async def _yt_call(fn, *args):
    global _LAST_CALL_TS
    async with _YT_SEMAPHORE:
        gap = time.time() - _LAST_CALL_TS
        if gap < _MIN_GAP:
            await asyncio.sleep(_MIN_GAP - gap)
        _LAST_CALL_TS = time.time()
        return await asyncio.to_thread(fn, *args)

# ==================== yt-dlp core ====================
def _pick_thumb(thumbs, vid):
    if thumbs:
        for t in reversed(thumbs):
            u = t.get("url") or ""
            if u and "vi_webp" not in u: return u
    return f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"

def _search_sync(query, limit=24):
    opts = _make_search_opts()
    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(f"ytsearch{limit}:{query}", download=False)
    entries = info.get("entries", []) if info else []
    out = []
    for e in entries:
        if not e: continue
        vid = e.get("id") or e.get("video_id")
        if not vid: continue
        out.append({
            "id": vid, "title": e.get("title") or "Untitled",
            "channel": e.get("uploader") or e.get("channel") or "Unknown",
            "channel_id": e.get("channel_id") or e.get("uploader_id") or "",
            "duration": int(e.get("duration") or 0),
            "view_count": int(e.get("view_count") or 0),
            "thumbnail": _pick_thumb(e.get("thumbnails") or [], vid),
            "url": f"https://www.youtube.com/watch?v={vid}",
        })
    return out

def _stream_sync(video_id):
    url = f"https://www.youtube.com/watch?v={video_id}"
    opts = _make_stream_opts()
    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=False)
    if not info: return None

    is_live = bool(info.get("is_live") or info.get("live_status") in ("is_live", "is_upcoming"))
    stream_url = info.get("url")
    formats = info.get("formats") or []

    if not stream_url:
        progressive = [f for f in formats
            if f.get("vcodec") and f["vcodec"] != "none"
            and f.get("acodec") and f["acodec"] != "none"
            and f.get("url")
            and (f.get("ext") == "mp4" or "mp4" in (f.get("container") or ""))]
        progressive.sort(key=lambda f: f.get("height") or 0, reverse=True)
        if progressive: stream_url = progressive[0]["url"]

    if not stream_url:
        any_combined = [f for f in formats
            if f.get("vcodec") and f["vcodec"] != "none"
            and f.get("acodec") and f["acodec"] != "none"
            and f.get("url")]
        any_combined.sort(key=lambda f: f.get("height") or 0, reverse=True)
        if any_combined: stream_url = any_combined[0]["url"]

    if not stream_url:
        for f in formats:
            if "m3u8" in (f.get("protocol") or "").lower() and f.get("url"):
                stream_url = f["url"]; break

    if not stream_url:
        stream_url = info.get("manifest_url") or info.get("hls_url")

    is_hls = bool(stream_url and ".m3u8" in stream_url)
    return {
        "stream_url": stream_url, "is_live": is_live, "is_hls": is_hls,
        "title": info.get("title"),
        "channel": info.get("uploader") or info.get("channel"),
        "channel_id": info.get("channel_id"),
        "duration": int(info.get("duration") or 0),
        "thumbnail": _pick_thumb(info.get("thumbnails") or [], info.get("id") or video_id),
        "description": info.get("description") or "",
        "view_count": int(info.get("view_count") or 0),
        "like_count": int(info.get("like_count") or 0),
        "upload_date": info.get("upload_date") or "",
    }

async def yt_search(query, limit=24, ttl=TTL_SEARCH):
    key = f"search::{query}::{limit}"
    hit = await cache_get(key)
    if hit is not None: return hit
    try:
        data = await _yt_call(_search_sync, query, limit)
    except Exception as e:
        logger.warning(f"search failed for '{query}': {str(e)[:200]}")
        return []
    if data: await cache_set(key, data, ttl)
    return data

_STREAM_LOCKS: dict = {}

def _get_stream_lock(video_id):
    lock = _STREAM_LOCKS.get(video_id)
    if lock is None:
        lock = asyncio.Lock(); _STREAM_LOCKS[video_id] = lock
    return lock

async def resolve_stream(video_id, force=False):
    key = f"stream::{video_id}"
    if not force:
        hit = await cache_get(key)
        if hit is not None: return hit
    lock = _get_stream_lock(video_id)
    async with lock:
        if not force:
            hit = await cache_get(key)
            if hit is not None: return hit
        try:
            data = await _yt_call(_stream_sync, video_id)
        except Exception as e:
            logger.warning(f"yt-dlp resolve failed for {video_id}: {str(e)[:200]}")
            data = None
        if data and data.get("stream_url"):
            await cache_set(key, data, TTL_STREAM)
        return data

# ==================== Auth ====================
def hash_password(p): return bcrypt.hashpw(p.encode(), bcrypt.gensalt()).decode()
def verify_password(p, h):
    try: return bcrypt.checkpw(p.encode(), h.encode())
    except Exception: return False
def make_token(uid, did, role):
    return jwt.encode({"uid": uid, "did": did, "role": role,
        "exp": datetime.now(timezone.utc) + timedelta(days=JWT_EXPIRE_DAYS)},
        JWT_SECRET, algorithm=JWT_ALGO)
def decode_token(t): return jwt.decode(t, JWT_SECRET, algorithms=[JWT_ALGO])

async def get_current_user(creds: Optional[HTTPAuthorizationCredentials] = Depends(bearer),
                           x_device_id: Optional[str] = Header(None)):
    if not creds: raise HTTPException(401, "Not authenticated")
    try: payload = decode_token(creds.credentials)
    except jwt.ExpiredSignatureError: raise HTTPException(401, "Token expired")
    except Exception: raise HTTPException(401, "Invalid token")
    user = await db.users.find_one({"id": payload["uid"]}, {"_id": 0})
    if not user: raise HTTPException(401, "User not found")
    if not user.get("active", True): raise HTTPException(403, "Account disabled")
    if user.get("role") != "admin":
        bound = user.get("device_id"); token_did = payload.get("did")
        if bound and token_did and bound != token_did:
            raise HTTPException(409, "DEVICE_MISMATCH")
        if x_device_id and bound and x_device_id != bound:
            raise HTTPException(409, "DEVICE_MISMATCH")
    return user

async def require_admin(user=Depends(get_current_user)):
    if user.get("role") != "admin": raise HTTPException(403, "Admin only")
    return user

# ==================== Models ====================
class LoginIn(BaseModel):
    email: EmailStr; password: str; device_id: str
class CreateUserIn(BaseModel):
    email: EmailStr; password: str; name: Optional[str] = ""
class UpdateUserIn(BaseModel):
    name: Optional[str] = None; password: Optional[str] = None
    active: Optional[bool] = None; reset_device: Optional[bool] = None
class VideoRef(BaseModel):
    id: str; title: str; channel: str = ""
    duration: int = 0; thumbnail: str = ""; view_count: int = 0
class HistoryIn(BaseModel):
    video: VideoRef; progress: float = 0.0
class TrendBoostIn(BaseModel):
    video_id: str; boost: int = 100

# ==================== Auth routes ====================
@api.post("/auth/login")
async def login(body: LoginIn):
    email = body.email.strip().lower()
    user = await db.users.find_one({"email": email})
    if not user or not verify_password(body.password, user.get("password_hash", "")):
        raise HTTPException(401, "Invalid email or password")
    if not user.get("active", True): raise HTTPException(403, "Account disabled by admin")
    role = user.get("role", "user")
    if role != "admin":
        bound = user.get("device_id")
        if bound and bound != body.device_id: raise HTTPException(409, "DEVICE_MISMATCH")
        if not bound:
            await db.users.update_one({"id": user["id"]}, {"$set": {
                "device_id": body.device_id,
                "device_bound_at": datetime.now(timezone.utc).isoformat()}})
    token = make_token(user["id"], body.device_id, role)
    return {"token": token, "user": {"id": user["id"], "email": user["email"],
            "name": user.get("name", ""), "role": role}}

@api.get("/auth/me")
async def me(user=Depends(get_current_user)):
    return {"id": user["id"], "email": user["email"],
            "name": user.get("name", ""), "role": user.get("role", "user")}

@api.post("/auth/logout")
async def logout(user=Depends(get_current_user)):
    if user.get("role") != "admin":
        await db.users.update_one({"id": user["id"]}, {"$set": {"device_id": None}})
    return {"ok": True}

# ==================== Admin ====================
@api.get("/admin/users")
async def admin_list_users(_=Depends(require_admin)):
    items = await db.users.find({}, {"_id": 0, "password_hash": 0}).sort("created_at", -1).to_list(1000)
    return {"users": items}

@api.post("/admin/users")
async def admin_create_user(body: CreateUserIn, _=Depends(require_admin)):
    email = body.email.strip().lower()
    if await db.users.find_one({"email": email}): raise HTTPException(409, "Email already exists")
    doc = {"id": str(uuid.uuid4()), "email": email, "name": body.name or "",
           "password_hash": hash_password(body.password), "role": "user",
           "active": True, "device_id": None,
           "created_at": datetime.now(timezone.utc).isoformat()}
    await db.users.insert_one(doc)
    doc.pop("password_hash", None)
    return {"user": doc}

@api.patch("/admin/users/{user_id}")
async def admin_update_user(user_id: str, body: UpdateUserIn, _=Depends(require_admin)):
    update = {}
    if body.name is not None: update["name"] = body.name
    if body.password: update["password_hash"] = hash_password(body.password)
    if body.active is not None: update["active"] = body.active
    if body.reset_device: update["device_id"] = None
    if not update: return {"ok": True}
    res = await db.users.update_one({"id": user_id, "role": {"$ne": "admin"}}, {"$set": update})
    if res.matched_count == 0: raise HTTPException(404, "User not found")
    return {"ok": True}

@api.delete("/admin/users/{user_id}")
async def admin_delete_user(user_id: str, _=Depends(require_admin)):
    res = await db.users.delete_one({"id": user_id, "role": {"$ne": "admin"}})
    if res.deleted_count == 0: raise HTTPException(404, "User not found")
    await db.history.delete_many({"user_id": user_id})
    await db.likes.delete_many({"user_id": user_id})
    await db.watch_later.delete_many({"user_id": user_id})
    return {"ok": True}

@api.post("/admin/trends/boost")
async def admin_boost_trend(body: TrendBoostIn, _=Depends(require_admin)):
    await db.trend_boosts.update_one({"video_id": body.video_id},
        {"$inc": {"boost": body.boost},
         "$set": {"updated_at": datetime.now(timezone.utc).isoformat()}}, upsert=True)
    return {"ok": True}

@api.get("/admin/trends/boosted")
async def admin_list_boosted(_=Depends(require_admin)):
    items = await db.trend_boosts.find({}, {"_id": 0}).sort("boost", -1).to_list(200)
    return {"boosts": items}

@api.get("/admin/cache/stats")
async def admin_cache_stats(_=Depends(require_admin)):
    total = await db.yt_cache.count_documents({})
    fresh = await db.yt_cache.count_documents({"expires_at": {"$gt": time.time()}})
    return {"memory_cache": len(_MEM_CACHE), "db_cache_total": total,
            "db_cache_fresh": fresh, "cookies_loaded": YT_COOKIES_FILE is not None}

@api.post("/admin/cache/clear")
async def admin_cache_clear(_=Depends(require_admin)):
    _MEM_CACHE.clear()
    res = await db.yt_cache.delete_many({})
    return {"ok": True, "deleted": res.deleted_count}

# ==================== App routes ====================
@api.get("/")
async def root():
    return {"app": "Ryhavean YouTube", "status": "ok",
            "cookies_loaded": YT_COOKIES_FILE is not None}

@api.get("/search")
async def search(q: str = Query(..., min_length=1), limit: int = 24, user=Depends(get_current_user)):
    try:
        results = await yt_search(q, limit=min(max(limit, 1), 30))
        return {"query": q, "count": len(results), "results": results}
    except Exception as e:
        logger.exception("search failed")
        raise HTTPException(502, f"Search failed: {e}")

@api.get("/suggest")
async def suggest(q: str = Query(..., min_length=1), user=Depends(get_current_user)):
    url = "https://suggestqueries.google.com/complete/search"
    params = {"client": "youtube", "ds": "yt", "q": q, "hl": "en"}
    try:
        async with httpx.AsyncClient(timeout=8.0) as cx:
            r = await cx.get(url, params=params, headers={"User-Agent": LOCKED_UA})
        text = r.text
        start = text.find("["); end = text.rfind("]")
        import json as _json
        if start >= 0 and end > start:
            arr = _json.loads(text[start:end + 1])
            return {"suggestions": [s[0] for s in arr[1] if isinstance(s, list)][:10]}
    except Exception: pass
    return {"suggestions": []}

@api.get("/trending-keywords")
async def trending_keywords(_=Depends(get_current_user)):
    return {"keywords": ["Music", "Gaming", "News", "Sports", "Movies", "Live",
                         "Lo-fi", "Podcast", "Trailers", "Shorts", "Tech", "Comedy"]}

@api.get("/video/{video_id}")
async def video_meta(video_id: str, user=Depends(get_current_user)):
    key = f"info::{video_id}"
    hit = await cache_get(key)
    if hit: return hit
    data = await resolve_stream(video_id)
    if not data: raise HTTPException(404, "Video not found")
    out = {"id": video_id, "title": data.get("title"), "channel": data.get("channel"),
           "channel_id": data.get("channel_id"), "duration": data.get("duration"),
           "thumbnail": data.get("thumbnail"), "description": data.get("description"),
           "view_count": data.get("view_count"), "like_count": data.get("like_count"),
           "upload_date": data.get("upload_date")}
    await cache_set(key, out, TTL_INFO)
    return out

@api.get("/stream/{video_id}")
async def stream_meta(video_id: str, request: Request, proxy: int = 0, user=Depends(get_current_user)):
    data = await resolve_stream(video_id)
    if not data or not data.get("stream_url"):
        raise HTTPException(404, "Stream not found")
    is_hls = bool(data.get("is_hls"))
    is_live = bool(data.get("is_live"))
    if proxy and not is_hls:
        base = str(request.base_url).rstrip("/")
        out_url = f"{base}/api/proxy-stream/{video_id}"
    else:
        out_url = data["stream_url"]
    try:
        await db.play_counts.update_one({"id": video_id},
            {"$inc": {"plays": 1},
             "$set": {"title": data.get("title") or "", "channel": data.get("channel") or "",
                      "thumbnail": data.get("thumbnail") or "", "duration": data.get("duration") or 0,
                      "last_played": datetime.now(timezone.utc).isoformat()}}, upsert=True)
    except Exception: pass
    return {"video_id": video_id, "title": data.get("title"), "channel": data.get("channel"),
            "channel_id": data.get("channel_id"), "duration": data.get("duration"),
            "thumbnail": data.get("thumbnail"), "description": data.get("description"),
            "view_count": data.get("view_count"), "stream_url": out_url,
            "is_live": is_live, "is_hls": is_hls,
            "direct": (not bool(proxy)) or is_hls}

# ==================== Proxy stream ====================
_HTTP_TIMEOUT = httpx.Timeout(connect=10.0, read=None, write=30.0, pool=15.0)

@api.get("/proxy-stream/{video_id}")
async def proxy_stream(video_id: str, request: Request):
    range_header = request.headers.get("range")
    data = await resolve_stream(video_id)
    if not data or not data.get("stream_url"):
        raise HTTPException(404, "Stream not available")
    headers = {"User-Agent": LOCKED_UA, "Accept": "*/*"}
    if range_header: headers["Range"] = range_header
    upstream = httpx.AsyncClient(timeout=_HTTP_TIMEOUT, follow_redirects=True)
    req = upstream.build_request("GET", data["stream_url"], headers=headers)
    try:
        resp = await upstream.send(req, stream=True)
    except Exception:
        await upstream.aclose()
        raise HTTPException(502, "Upstream error")
    if resp.status_code in (403, 410):
        await resp.aclose(); await upstream.aclose()
        data = await resolve_stream(video_id, force=True)
        if not data or not data.get("stream_url"):
            raise HTTPException(404, "Stream re-resolve failed")
        upstream = httpx.AsyncClient(timeout=_HTTP_TIMEOUT, follow_redirects=True)
        req = upstream.build_request("GET", data["stream_url"], headers=headers)
        resp = await upstream.send(req, stream=True)

    async def _body():
        try:
            async for chunk in resp.aiter_raw(): yield chunk
        finally:
            try: await resp.aclose()
            except Exception: pass
            try: await upstream.aclose()
            except Exception: pass

    pass_headers = {}
    for h in ("content-type", "content-length", "content-range",
              "accept-ranges", "etag", "last-modified"):
        v = resp.headers.get(h)
        if v: pass_headers[h.title()] = v
    pass_headers.setdefault("Accept-Ranges", "bytes")
    pass_headers.setdefault("Cache-Control", "no-store")
    return StreamingResponse(_body(), status_code=resp.status_code, headers=pass_headers,
                             media_type=pass_headers.get("Content-Type", "video/mp4"))

# ==================== Recommendations ====================
@api.get("/recommendations")
async def recommendations(video_id: Optional[str] = None, user=Depends(get_current_user)):
    queries: List[str] = []; seed_title = None
    if video_id:
        info = await db.play_counts.find_one({"id": video_id}, {"_id": 0, "title": 1, "channel": 1})
        if info:
            seed_title = info.get("title")
            if info.get("channel"): queries.append(info["channel"])
    history = await db.history.find({"user_id": user["id"]}, {"_id": 0}).sort("played_at", -1).to_list(5)
    for h in history:
        if h.get("channel"): queries.append(h["channel"])
    if not queries: queries = ["trending", "music", "news"]
    if seed_title: queries.insert(0, seed_title)
    seen = set(); final: List[dict] = []
    for q in queries[:3]:
        try:
            res = await yt_search(q, limit=12)
            for r in res:
                if r["id"] == video_id or r["id"] in seen: continue
                seen.add(r["id"]); final.append(r)
        except Exception: continue
    boosted = await db.trend_boosts.find({}, {"_id": 0}).sort("boost", -1).to_list(20)
    if boosted:
        boost_ids = {b["video_id"] for b in boosted}
        boosted_items = [v for v in final if v["id"] in boost_ids]
        rest = [v for v in final if v["id"] not in boost_ids]
        final = boosted_items + rest
    return {"results": final[:30]}

# ==================== Home feed ====================
HOME_QUERIES = {
    "trending": "trending videos today",
    "music": "popular music videos",
    "gaming": "top gaming videos",
    "news": "world news today",
    "movies": "movie trailers 2025",
    "live": "live streams now",
}

@api.get("/home")
async def home_feed(user=Depends(get_current_user)):
    sections = {}
    async def _fetch(name, q):
        try: sections[name] = await yt_search(q, limit=12, ttl=TTL_FEATURED)
        except Exception: sections[name] = []
    await asyncio.gather(*[_fetch(n, q) for n, q in HOME_QUERIES.items()])
    cw = await db.history.find({"user_id": user["id"], "progress": {"$gt": 5}},
                               {"_id": 0}).sort("played_at", -1).to_list(10)
    return {"sections": sections, "continue_watching": cw}

@api.get("/categories")
async def categories(_=Depends(get_current_user)):
    return {"categories": list(HOME_QUERIES.keys())}

@api.get("/category/{name}")
async def category_feed(name: str, user=Depends(get_current_user)):
    q = HOME_QUERIES.get(name, name)
    res = await yt_search(q, limit=24, ttl=TTL_FEATURED)
    return {"name": name, "results": res}

# ==================== History / Likes / Watch later ====================
@api.post("/history")
async def add_history(body: HistoryIn, user=Depends(get_current_user)):
    doc = {"user_id": user["id"], "video_id": body.video.id,
           "title": body.video.title, "channel": body.video.channel,
           "duration": body.video.duration, "thumbnail": body.video.thumbnail,
           "view_count": body.video.view_count, "progress": body.progress,
           "played_at": datetime.now(timezone.utc).isoformat()}
    await db.history.update_one({"user_id": user["id"], "video_id": body.video.id},
                                {"$set": doc}, upsert=True)
    return {"ok": True}

@api.get("/history")
async def list_history(user=Depends(get_current_user), limit: int = 50):
    items = await db.history.find({"user_id": user["id"]}, {"_id": 0}).sort("played_at", -1).to_list(limit)
    return {"history": items}

@api.delete("/history/{video_id}")
async def delete_history_item(video_id: str, user=Depends(get_current_user)):
    await db.history.delete_one({"user_id": user["id"], "video_id": video_id})
    return {"ok": True}

@api.delete("/history")
async def clear_history(user=Depends(get_current_user)):
    await db.history.delete_many({"user_id": user["id"]})
    return {"ok": True}

@api.post("/likes")
async def add_like(body: VideoRef, user=Depends(get_current_user)):
    doc = {"user_id": user["id"], "video_id": body.id,
           "title": body.title, "channel": body.channel,
           "duration": body.duration, "thumbnail": body.thumbnail,
           "view_count": body.view_count,
           "created_at": datetime.now(timezone.utc).isoformat()}
    await db.likes.update_one({"user_id": user["id"], "video_id": body.id},
                              {"$set": doc}, upsert=True)
    return {"ok": True}

@api.delete("/likes/{video_id}")
async def remove_like(video_id: str, user=Depends(get_current_user)):
    await db.likes.delete_one({"user_id": user["id"], "video_id": video_id})
    return {"ok": True}

@api.get("/likes")
async def list_likes(user=Depends(get_current_user)):
    items = await db.likes.find({"user_id": user["id"]}, {"_id": 0}).sort("created_at", -1).to_list(500)
    return {"likes": items, "ids": [i["video_id"] for i in items]}

@api.post("/watch-later")
async def add_watch_later(body: VideoRef, user=Depends(get_current_user)):
    doc = {"user_id": user["id"], "video_id": body.id,
           "title": body.title, "channel": body.channel,
           "duration": body.duration, "thumbnail": body.thumbnail,
           "view_count": body.view_count,
           "created_at": datetime.now(timezone.utc).isoformat()}
    await db.watch_later.update_one({"user_id": user["id"], "video_id": body.id},
                                    {"$set": doc}, upsert=True)
    return {"ok": True}

@api.delete("/watch-later/{video_id}")
async def remove_watch_later(video_id: str, user=Depends(get_current_user)):
    await db.watch_later.delete_one({"user_id": user["id"], "video_id": video_id})
    return {"ok": True}

@api.get("/watch-later")
async def list_watch_later(user=Depends(get_current_user)):
    items = await db.watch_later.find({"user_id": user["id"]}, {"_id": 0}).sort("created_at", -1).to_list(500)
    return {"items": items}

# ==================== Background tasks ====================
async def _prune_cache_loop():
    while True:
        try:
            await asyncio.sleep(60 * 60)
            now = time.time()
            res = await db.yt_cache.delete_many({"expires_at": {"$lt": now}})
            if res.deleted_count:
                logger.info(f"[cache] pruned {res.deleted_count} expired entries")
        except asyncio.CancelledError: break
        except Exception as e:
            logger.warning(f"[cache] prune error: {e}")

async def _ensure_admin():
    existing = await db.users.find_one({"email": ADMIN_EMAIL.lower()})
    if existing:
        if not verify_password(ADMIN_PASSWORD, existing.get("password_hash", "")):
            await db.users.update_one({"id": existing["id"]},
                {"$set": {"password_hash": hash_password(ADMIN_PASSWORD),
                          "role": "admin", "active": True}})
        return
    doc = {"id": str(uuid.uuid4()), "email": ADMIN_EMAIL.lower(), "name": "Admin",
           "password_hash": hash_password(ADMIN_PASSWORD), "role": "admin",
           "active": True, "device_id": None,
           "created_at": datetime.now(timezone.utc).isoformat()}
    await db.users.insert_one(doc)
    logger.info("Admin user seeded: %s", ADMIN_EMAIL)

async def _ensure_indexes():
    try:
        await db.yt_cache.create_index("expires_at")
        await db.users.create_index("email", unique=True)
        await db.history.create_index([("user_id", 1), ("played_at", -1)])
        await db.likes.create_index([("user_id", 1), ("video_id", 1)], unique=True)
        await db.watch_later.create_index([("user_id", 1), ("video_id", 1)], unique=True)
    except Exception as e:
        logger.warning(f"index creation: {e}")

app.include_router(api)
app.add_middleware(CORSMiddleware,
    allow_origins=os.environ.get("CORS_ORIGINS", "*").split(","),
    allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

_bg_tasks: List[asyncio.Task] = []

@app.on_event("startup")
async def _startup():
    await _ensure_admin()
    await _ensure_indexes()
    _bg_tasks.append(asyncio.create_task(_prune_cache_loop()))
    logger.info(f"[startup] cookies={'YES' if YT_COOKIES_FILE else 'NO'}")

@app.on_event("shutdown")
async def _shutdown():
    for t in _bg_tasks:
        t.cancel()
    client.close()
